export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
export const ADD_TICKET_FAIL = 'ADD_TICKET_FAIL';
export const START_ADDING_TICKET = 'START_GETTING_TICKET';

export const SAVE_TICKET = 'SAVE_TICKET';